# Default parameters, even this default build is excluded in the build
# matrix below. We define so Travis doesn't think this is a Ruby
# project.
os: linux
language: c
compiler: gcc

# Define the default CFLAGS used by all builds as a YAML anchor.
default-cflags: &default-cflags
  CFLAGS="-Wall -Wextra -Werror -Wno-unused-parameter -Wno-unused-function -std=gnu99"

# The default build is Linux with gcc. Add additional builds to the
# matrix here.
matrix:
  # Exclude the default build so any the builds in the matrix will be done.
  exclude:
    - os: linux
      compiler: gcc
  include:
    # Linux, gcc, cocci tests enabled.
    - os: linux
      compiler: gcc
      env:
        - NAME="linux,gcc,install"
        - *default-cflags
        - TEST_INSTALL="1"
    # Linux, clang. For this build we'll also enable -Wshadow.
    - os: linux
      compiler: clang
      env:
        - NAME="linux,clang,deb"
        - *default-cflags
        - EXTRA_CFLAGS="-Wshadow"
        - TEST_DEB="1"

# Change this to your needs
script:
  - sh autogen.sh
  - ./configure
  - make
  - make distcheck
  - |
    if [[ "$TEST_DEB" == "1" ]]; then
        dpkg-buildpackage -us -uc
    fi
  - |
    if [[ "$TEST_INSTALL" == "1" ]]; then
        fakeroot installer/install.sh --prefix /tmp/vuurmuur/ --defaults --install
    fi

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential autoconf automake libtool make fakeroot debhelper libncurses5-dev libnetfilter-log-dev libmnl-dev libnetfilter-conntrack-dev

